adminUser: admin
adminPassword: admin123  # change this for security!

service:
  type: LoadBalancer  # expose Grafana with LB for easy access

persistence:
  enabled: false  # disable persistence, enable for production use

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
