name: 📊 Deploy Monitoring Stack (Prometheus & Grafana)

on:
  workflow_run:
    workflows: ["🚀 Deploy App to EKS"]
    types:
      - completed

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.14.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Install Prometheus via Helm
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace --set server.persistentVolume.storageClass=gp2

      - name: Install Grafana via Helm
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update
          helm install grafana grafana/grafana --namespace monitoring --create-namespace

      - name: Verify Deployments
        run: |
          kubectl get all -n monitoring

      # Slack Notification on Failure
      - name: Send Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":x: *📊 Deploy Monitoring Stack (Prometheus & Grafana) failed* for repository: *${{ github.repository }}* on branch *${{ github.ref }}*."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Slack Notification on Success
      - name: Send Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":white_check_mark: Successfully 📊 Deploy Monitoring Stack (Prometheus & Grafana) for *${{ github.repository }}*."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}          
